server:
  port: 9999
  servlet:
    context-path: /ontheblock/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ontheblock?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ssafy
    password: ssafy
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3600
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000 # ??? ??
    open-in-view: false
  sql:
    init:
      encoding: UTF-8


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

kakao:
  api:
    key: b55f07cef8bd406869c7d26fe0bb8975
    host: kapi.kakao.com
  auth:
    host: kauth.kakao.com
  url:
    redirect: http://localhost:9999/ontheblock/api/kakao/redirect

google:
  client:
    id: 668539871824-pkb9kocndjjog9src6s8s27jp4cjc3j4.apps.googleusercontent.com
    secret: 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
  auth:
    host: accounts.google.com
  api:
    host: oauth2.googleapis.com
  url:
    redirect: http://localhost:9999/ontheblock/api/google/redirect

front:
  scheme: http
  host: localhost:5173
  url:
    home: http://localhost:5173
    login: http://localhost:5173/members/login
    bridge: http://localhost:5173/bridge

recommend:
  url: http://j9a402.p.ssafy.io:8000

cloud:
  aws:
    credentials:
      accessKey: AKIARWWMRYN4MBQSQVPF
      secretKey: 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
    s3:
      bucket: project-ontheblock
    region:
      static: ap-northeast-2
    stack:
      auto: false